apiVersion: v1
kind: Namespace
metadata:
  name: solution-based-monitoring-ignore
  labels:
    syn_team: nunki
    vshn_net_solution_monitoring: "other"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: failing-pdb
  namespace: solution-based-monitoring-ignore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: failing-app
  template:
    metadata:
      labels:
        app: failing-app
    spec:
      containers:
        - name: failing-container
          image: busybox
          command: ["sh", "-c", "exit 1"]
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: failing-pdb
  namespace: solution-based-monitoring-ignore
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: failing-app
