apiVersion: v1
kind: Namespace
metadata:
  name: solution-based-monitoring-fail-do
  labels:
    syn_team: nunki
    vshn_net_solution_monitoring: "test-solution-base-monitoring"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pending-pod
  namespace: solution-based-monitoring-fail-do
spec:
  replicas: 1
  selector:
    matchLabels:
      app: failing-app
  template:
    metadata:
      labels:
        app: failing-app
    spec:
      containers:
        - name: failing-container
          image: busybox:nonexistent-tag-12345
