apiVersion: v1
kind: Namespace
metadata:
  name: solution-based-monitoring-fail-do
  labels:
    syn_team: nunki
    vshn_net_solution_monitoring: "test-solution-base-monitoring"
---
apiVersion: v1
kind: Service
metadata:
  name: failing-statefulset
  namespace: solution-based-monitoring-fail-do
spec:
  clusterIP: None
  selector:
    app: failing-app
  ports:
    - port: 80
      name: web
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: failing-statefulset
  namespace: solution-based-monitoring-fail-do
spec:
  serviceName: failing-statefulset
  replicas: 1
  selector:
    matchLabels:
      app: failing-app
  template:
    metadata:
      labels:
        app: failing-app
    spec:
      containers:
        - name: failing-container
          image: busybox
          command: ["sh", "-c", "exit 1"]
