apiVersion: v1
kind: Namespace
metadata:
  name: solution-based-monitoring-ignore
  labels:
    syn_team: nunki
    vshn_net_solution_monitoring: "other"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: failing-job
  namespace: solution-based-monitoring-ignore
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: failing-container
          image: busybox
          command: ["sh", "-c", "sleep infinity"]
